### PR TITLE
Run SqueakJS on Electron.

### PR DESCRIPTION
**Pull request by jsparkes**
Hi.  I've got a configuration that will run SqueakJS on electron.
It runs quite well, with performance similar to chrome.
There are flashing scrollbars with graphic updates.
I don't actually know anything Electron, I just followed the sample.

### CODE REVIEW

**Comment by jsparkes** [comment]
It doesn't restart the image when I click in the top block, it causes a download of the file.  I'll see if I can solve it.

**Comment by bertfreudenberg** [comment]
Have you seen the NW.js app in `/standalone`? Is there an advantage to using Electron?

**Comment by jsparkes** [comment]
How do you run the standalone version?   There's nothing in the Makefile, so I thought it was incomplete.  I couldn't figure out how to start it.

Electron provides a browser environment to run in, on top of node.  I saw an older message message in the mailing list where someone had made it run with electron, but then didn't send the code in.  I figured it would be an easy place to start.

The best thing for me to do is to add the electron config to the standalone directory.  I'll send another pull request when I get that working.

**Comment by bertfreudenberg** [comment]
@timfel care to comment?

**Comment by fniephaus** [comment]
I've also done an Electron-based SqueakJS app. But to be honest, I didn't have a proper use case, so I ditched the idea. I guess it's up to @bertfreudenberg if and how to keep SqueakJS wrappers/adapters. Would be nice if done consistently, but I'm also not sure if everything should be in one and the same repo.

**Pull request closed without merging**
