### PR TITLE
Enable keyboard input on touch devices

### PR DESCRIPTION
**Pull request by fniephaus**
Work in progress. Not ready to merge yet.

This aims to address #4.

Already working on:
- iPad 4 Retina
- iPhone 6

Not working on:
- Windows Phone
- Android

Feel free to comment on the below :smiley:

### CODE REVIEW

**Comment by bertfreudenberg** [comment]
Works on my iPad, nice!

But I think a floating "keyboard button" to bring up the keyboard would be better (more discoverable). Additionally, we need a "cmd" button, so we can use _cmd-p_ for print-it etc. (as I had it in the iPad version of Etoys https://www.youtube.com/watch?v=gYrp31fH-Jk and we might also learn from Pyonkee, one of the few Squeak apps in the AppStore http://softumeya.com/pyonkee/en/)

Speaking of which, if we had that, then _cmd-tap_ could mean right click too, obviously ...

Also, in newer Squeak images we actually could get a notification when a text morph is focused (via `compositionWindowManager`) and pop up the keyboard automatically. We just need to hack the platform detection (i.e. change the 5th literal from `'Win32'` to `'Web'`) and fake `ImmWin32Plugin.primSetCompositionWindowPosition`.

**Comment by fniephaus** [comment]
Two screenshots taken from the TeamViewer iOS app:



Maybe something similar to this?

**Comment by bertfreudenberg** [comment]
Looks good to me.

**Comment by fniephaus** [comment]
How about a virtual game controller like this?
https://github.com/austinhallock/html5-virtual-game-controller#examples

**Comment by bertfreudenberg** [comment]
Well we do need a way to emulate keys that are not on the system keyboard, e.g. cursor keys and modifiers. So yeah, something like the game controller may be nice.

**Comment by fniephaus** [comment]
How about this (only visible on touch devices):


Click on *Mouse*:


Click on *Keyboard*

**Comment by bertfreudenberg** [comment]
Hi Fabio, thank you for the design studies and initial implementation! I think the keyboard button idea is still valid, but the on-screen joystick is not so nice after all. We do have a better touch handling now (8262926740f3ef14c56501466c523dae5bbd9f5d) so for the time being I'm closing this. We still want to add in keyboard support, maybe we can salvage something from this patch. Thank you so much!

**Pull request closed without merging**
